starter = input ("Hello, what is your favourite starter?")
mainC = input ("What is your favourite main course?")
pud = input ("What do you like for pudding?")
drink = input ("Finally, what do you enjoy drinking with meals?")
print (" I bet you would enjoy,",starter,  "," ,mainC, "," ,pud, "and", drink)
